Catalog
Rostyslav-Stetsyk/project-group-15 pull request #5
Opened 2023-04-20 20:51 UTC by Pavlo2005

ready version of the catalog with stubs instead of the main classes, waiting for verification

2023-04-21 09:21 UTC, SashaKuh requested changes
в style.css видали те що ти додав, так само і в index.html, але зі всім іншим добре зпрацювався, я тільки б хтів що б  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1); було в root

2023-04-21 14:05 UTC, SashaKuh approved these changes
Add :
- catalog.css
- catalog.html

2023-04-21 20:14 UTC, Rostyslav-Stetsyk requested changes
В style.css потрібно на місце коментаря /* catalog */ вставити імпорт стилів каталогу, не можна створювати нові рядки у файлах style.css index.html

2023-04-21 20:14 UTC, Rostyslav-Stetsyk commented on src/css/styles.css
> +@import url('./catalog.css');
Імпортувати потрібно на місці коментаря, не можна створювати нові рядки у файлах style.css index.html

2023-04-22 07:32 UTC, SashaKuh approved these changes
Fix :
- index.html and style.css

2023-04-22 07:56 UTC, merged